const defaultTerritories = [
  {
    name: 'Scandinavia',
    control: 100,
    income: 800,
    influence: 5000,
  },
  {
    name: 'Netherlands',
    control: 100,
    income: 750,
    influence: 5000,
  },
  {
    name: 'Interim',
    control: 100,
    income: 700,
    influence: 4000,
  },
  {
    name: 'balkans',
    control: 100,
    income: 600,
    influence: 3500,
  },
  {
    name: 'SouthSpain',
    control: 100,
    income: 240,
    influence: 3300,
    owner: 'Spain',
  },
  {
    name: 'NorthSpain',
    control: 100,
    income: 240,
    influence: 3300,
    owner: 'Spain',
  },
  {
    name: 'WestFrance',
    control: 100,
    income: 450,
    influence: 3500,
    owner: 'France',
  },
  {
    name: 'EastFrance',
    control: 100,
    income: 450,
    influence: 3500,
    owner: 'France',
  },
  {
    name: 'SouthFrance',
    control: 100,
    income: 450,
    influence: 3500,
    owner: 'France',
  },
  {
    name: 'WestGermany',
    control: 100,
    income: 580,
    influence: 2800,
    owner: 'Germany',
  },
  {
    name: 'SouthGermany',
    control: 100,
    income: 580,
    influence: 2800,
    owner: 'Germany',
  },
  {
    name: 'EastGermany',
    control: 100,
    income: 580,
    influence: 2800,
    owner: 'Germany',
  },
  {
    name: 'SouthItaly',
    control: 100,
    income: 430,
    influence: 3800,
    owner: 'Italy',
  },
  {
    name: 'NorthItaly',
    control: 100,
    income: 430,
    influence: 3800,
    owner: 'Italy',
  },
  {
    name: 'EastRussia',
    control: 100,
    income: 235,
    influence: 8000,
    owner: 'Russia',
  },
  {
    name: 'WestRussia',
    control: 100,
    income: 235,
    influence: 8000,
    owner: 'Russia',
  },
  {
    name: 'NorthUK',
    control: 100,
    income: 333,
    influence: 3200,
    owner: 'UK',
  },
  {
    name: 'MidUK',
    control: 100,
    income: 333,
    influence: 3200,
    owner: 'UK',
  },
  {
    name: 'SouthUK',
    control: 100,
    income: 333,
    influence: 3200,
    owner: 'UK',
  },
];

export default defaultTerritories;
